default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: es_sample_development

test:
  <<: *default
  database: es_sample_test

production:
  <<: *default
  database: es_sample_production
